"""
keygen.py

Generates keypairs. Tries PQC libraries (XMSS/LMS/SPHINCS) if available.
If not found, falls back to Ed25519 (NOT quantum-safe) for demonstration.

WARNING: For real, production post-quantum safety, install and use a
well-reviewed XMSS/LMS/SPHINCS implementation.
"""

import os
import json
import time
from pathlib import Path

KEY_DIR = Path(__file__).resolve().parents[1] / "keys"
KEY_DIR.mkdir(parents=True, exist_ok=True)

def _save_keypair(name, public_bytes, private_bytes, meta):
    ts = int(time.time())
    pub_path = KEY_DIR / f"{name}_pub_{ts}.pem"
    priv_path = KEY_DIR / f"{name}_priv_{ts}.pem"
    meta_path = KEY_DIR / f"{name}_meta_{ts}.json"
    pub_path.write_bytes(public_bytes)
    priv_path.write_bytes(private_bytes)
    meta_path.write_text(json.dumps(meta, indent=2))
    return str(pub_path), str(priv_path), str(meta_path)

def generate_keypair(algo_preference=("xmss","lms","sphincs","ed25519")):
    """
    Try PQC libs in preference order. If none present, create Ed25519 keypair.
    Returns dict: {algo, pub_path, priv_path, meta_path}
    """
    # Try XMSS (pyxmss)
    try:
        import pyxmss
        # hypothetical API usage — adjust to library you have
        sk, pk = pyxmss.generate_keypair()
        pub_bytes = pk.to_bytes()
        priv_bytes = sk.to_bytes()
        meta = {"algo":"xmss", "note":"Generated by pyxmss (if installed)."}
        pub_path, priv_path, meta_path = _save_keypair("xmss", pub_bytes, priv_bytes, meta)
        return {"algo":"xmss","pub":pub_path,"priv":priv_path,"meta":meta_path}
    except Exception:
        pass

    # Try LMS
    try:
        import pylms
        sk, pk = pylms.generate_keypair()
        pub_bytes = pk.to_bytes()
        priv_bytes = sk.to_bytes()
        meta = {"algo":"lms", "note":"Generated by pylms (if installed)."}
        pub_path, priv_path, meta_path = _save_keypair("lms", pub_bytes, priv_bytes, meta)
        return {"algo":"lms","pub":pub_path,"priv":priv_path,"meta":meta_path}
    except Exception:
        pass

    # Try SPHINCS (pyspx)
    try:
        import pyspx
        # hypothetical usage:
        sk = pyspx.generate_secret_key()
        pk = pyspx.derive_public_key(sk)
        pub_bytes = pk
        priv_bytes = sk
        meta = {"algo":"sphincs", "note":"Generated by pyspx (if installed)."}
        pub_path, priv_path, meta_path = _save_keypair("sphincs", pub_bytes, priv_bytes, meta)
        return {"algo":"sphincs","pub":pub_path,"priv":priv_path,"meta":meta_path}
    except Exception:
        pass

    # FALLBACK: Ed25519 (NOT PQC) — demonstration only
    from cryptography.hazmat.primitives.asymmetric import ed25519
    from cryptography.hazmat.primitives import serialization

    sk = ed25519.Ed25519PrivateKey.generate()
    pk = sk.public_key()
    priv_bytes = sk.private_bytes(
        encoding = serialization.Encoding.PEM,
        format = serialization.PrivateFormat.PKCS8,
        encryption_algorithm = serialization.NoEncryption()
    )
    pub_bytes = pk.public_bytes(
        encoding = serialization.Encoding.PEM,
        format = serialization.PublicFormat.SubjectPublicKeyInfo
    )
    meta = {"algo":"ed25519-fallback", "note":"This is NOT quantum safe. Install XMSS/LMS for PQC."}
    pub_path, priv_path, meta_path = _save_keypair("ed25519", pub_bytes, priv_bytes, meta)
    return {"algo":"ed25519-fallback","pub":pub_path,"priv":priv_path,"meta":meta_path}
